/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author DELL
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    public JButton getBtnListaPersonas() {
        return JmenuCat;
    }

    public void setBtnListaPersonas(JButton BtnListaPersonas) {
        this.JmenuCat = BtnListaPersonas;
    }

    public JDesktopPane getDesktopPrincipal() {
        return DesktopPrincipal;
    }

    public void setDesktopPrincipal(JDesktopPane DesktopPrincipal) {
        this.DesktopPrincipal = DesktopPrincipal;
    }

    public JButton getBtnPersonas() {
        return btnPersonas;
    }

    public void setBtnPersonas(JButton btnPersonas) {
        this.btnPersonas = btnPersonas;
    }

    public JMenuItem getMenuCrudPersona() {
        return menuCrudPersona;
    }

    public void setMenuCrudPersona(JMenuItem menuCrudPersona) {
        this.menuCrudPersona = menuCrudPersona;
    }

    public JMenuItem getMenuListaPersonas() {
        return menuListaPersonas;
    }

    public void setMenuListaPersonas(JMenuItem menuListaPersonas) {
        this.menuListaPersonas = menuListaPersonas;
    }

    public JButton getBtnCProducto() {
        return BtnCProducto;
    }

    public void setBtnCProducto(JButton BtnCProducto) {
        this.BtnCProducto = BtnCProducto;
    }

    public JMenuItem getMenuCrearProducto() {
        return menuCrearProducto;
    }

    public void setMenuCrearProducto(JMenuItem menuCrearProducto) {
        this.menuCrearProducto = menuCrearProducto;
    }

    public JMenuItem getMenuSalirSistema() {
        return menuSalirSistema;
    }

    public void setMenuSalirSistema(JMenuItem menuSalirSistema) {
        this.menuSalirSistema = menuSalirSistema;
    }

    public JButton getBtnVenProdu() {
        return BtnVenProdu;
    }

    public void setBtnVenProdu(JButton BtnVenProdu) {
        this.BtnVenProdu = BtnVenProdu;
    }

    public JMenuItem getMenuVenderProducto() {
        return menuVenderProducto;
    }

    public void setMenuVenderProducto(JMenuItem menuVenderProducto) {
        this.menuVenderProducto = menuVenderProducto;
    }

    public JButton getJmenuCat() {
        return JmenuCat;
    }

    public void setJmenuCat(JButton JmenuCat) {
        this.JmenuCat = JmenuCat;
    }

    public JMenuItem getJmenuCatalogoP() {
        return JmenuCatalogoP;
    }

    public void setJmenuCatalogoP(JMenuItem JmenuCatalogoP) {
        this.JmenuCatalogoP = JmenuCatalogoP;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnPersonas = new javax.swing.JButton();
        JmenuCat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BtnCProducto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BtnVenProdu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DesktopPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCrudPersona = new javax.swing.JMenuItem();
        menuListaPersonas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCrearProducto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuVenderProducto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JmenuCatalogoP = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuSalirSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(211, 211, 211));
        jToolBar1.setRollover(true);

        btnPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-añadir-usuario-grupo-mujer-hombre-25.png"))); // NOI18N
        btnPersonas.setToolTipText("Crear Persona (Alt + Y)");
        btnPersonas.setFocusable(false);
        btnPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPersonas);

        JmenuCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-reporte-de-negocios-25.png"))); // NOI18N
        JmenuCat.setFocusable(false);
        JmenuCat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JmenuCat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(JmenuCat);

        jSeparator1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jToolBar1.add(jSeparator1);

        BtnCProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-más-25.png"))); // NOI18N
        BtnCProducto.setToolTipText("Crear Nuevo Producto (Ctrl + U)");
        BtnCProducto.setFocusable(false);
        BtnCProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BtnCProducto);
        jToolBar1.add(jSeparator2);

        BtnVenProdu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-buy-25.png"))); // NOI18N
        BtnVenProdu.setFocusable(false);
        BtnVenProdu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVenProdu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BtnVenProdu);

        jLabel1.setText("Mi Tienda 1.0");

        DesktopPrincipal.setBackground(new java.awt.Color(174, 169, 170));

        javax.swing.GroupLayout DesktopPrincipalLayout = new javax.swing.GroupLayout(DesktopPrincipal);
        DesktopPrincipal.setLayout(DesktopPrincipalLayout);
        DesktopPrincipalLayout.setHorizontalGroup(
            DesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopPrincipalLayout.setVerticalGroup(
            DesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jMenu1.setText("Persona");

        menuCrudPersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        menuCrudPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-añadir-usuario-grupo-mujer-hombre-25.png"))); // NOI18N
        menuCrudPersona.setText("Crear Persona");
        jMenu1.add(menuCrudPersona);

        menuListaPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-reporte-de-negocios-25.png"))); // NOI18N
        menuListaPersonas.setText("Lista Personas");
        jMenu1.add(menuListaPersonas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");

        menuCrearProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuCrearProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-más-25.png"))); // NOI18N
        menuCrearProducto.setText("Crear Producto");
        jMenu2.add(menuCrearProducto);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ventas");

        menuVenderProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-buy-25.png"))); // NOI18N
        menuVenderProducto.setText("Venta Producto");
        jMenu3.add(menuVenderProducto);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");

        JmenuCatalogoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-reporte-de-negocios-20.png"))); // NOI18N
        JmenuCatalogoP.setText("Catalogo");
        JmenuCatalogoP.setActionCommand("Catálogo");
        jMenu4.add(JmenuCatalogoP);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ayuda");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Salir");

        menuSalirSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icons/icons8-exit-25.png"))); // NOI18N
        menuSalirSistema.setText("Salir del Sisema");
        jMenu6.add(menuSalirSistema);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1316, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DesktopPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesktopPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCProducto;
    private javax.swing.JButton BtnVenProdu;
    private javax.swing.JDesktopPane DesktopPrincipal;
    private javax.swing.JButton JmenuCat;
    private javax.swing.JMenuItem JmenuCatalogoP;
    private javax.swing.JButton btnPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuCrearProducto;
    private javax.swing.JMenuItem menuCrudPersona;
    private javax.swing.JMenuItem menuListaPersonas;
    private javax.swing.JMenuItem menuSalirSistema;
    private javax.swing.JMenuItem menuVenderProducto;
    // End of variables declaration//GEN-END:variables
}
