/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author DELL
 */
public class ViewProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewProducto
     */
    public ViewProducto() {
        initComponents();
    }

    public JSpinner getSpnCantidadProducto() {
        return SpnCantidadProducto;
    }

    public void setSpnCantidadProducto(JSpinner SpnCantidadProducto) {
        this.SpnCantidadProducto = SpnCantidadProducto;
    }

    public JTextField getTxtBuscarProducto() {
        return TxtBuscarProducto;
    }

    public void setTxtBuscarProducto(JTextField TxtBuscarProducto) {
        this.TxtBuscarProducto = TxtBuscarProducto;
    }



    public JTextField getTxtIdProductot() {
        return TxtIdProductot;
    }

    public void setTxtIdProductot(JTextField TxtIdProductot) {
        this.TxtIdProductot = TxtIdProductot;
    }





    public JTextField getTxtPrecioProducto() {
        return TxtPrecioProducto;
    }

    public void setTxtPrecioProducto(JTextField TxtPrecioProducto) {
        this.TxtPrecioProducto = TxtPrecioProducto;
    }

    public JButton getBtnCancelarP() {
        return btnCancelarP;
    }

    public void setBtnCancelarP(JButton btnCancelarP) {
        this.btnCancelarP = btnCancelarP;
    }

    public JButton getBtnCrearProducto() {
        return btnCrearProducto;
    }

    public void setBtnCrearProducto(JButton btnCrearProducto) {
        this.btnCrearProducto = btnCrearProducto;
    }

    public JButton getBtnEditarProdcuto() {
        return btnEditarProdcuto;
    }

    public void setBtnEditarProdcuto(JButton btnEditarProdcuto) {
        this.btnEditarProdcuto = btnEditarProdcuto;
    }

    public JButton getBtnImprimirProducto() {
        return btnImprimirProducto;
    }

    public void setBtnImprimirProducto(JButton btnImprimirProducto) {
        this.btnImprimirProducto = btnImprimirProducto;
    }

    public JButton getBtnRemoverProducto() {
        return btnRemoverProducto;
    }

    public void setBtnRemoverProducto(JButton btnRemoverProducto) {
        this.btnRemoverProducto = btnRemoverProducto;
    }

    public JDialog getDlgDialogoProductos() {
        return dlgDialogoProductos;
    }

    public void setDlgDialogoProductos(JDialog dlgDialogoProductos) {
        this.dlgDialogoProductos = dlgDialogoProductos;
    }

    public JTable getTblProductos() {
        return tblProductos;
    }

    public void setTblProductos(JTable tblProductos) {
        this.tblProductos = tblProductos;
    }

    public JTextArea getTxtDescripcionProducto() {
        return txtDescripcionProducto;
    }

    public void setTxtDescripcionProducto(JTextArea txtDescripcionProducto) {
        this.txtDescripcionProducto = txtDescripcionProducto;
    }

    public JButton getBtnAceptarP() {
        return btnAceptarP;
    }

    public void setBtnAceptarP(JButton btnAceptarP) {
        this.btnAceptarP = btnAceptarP;
    }

    public JButton getBtnExaminar() {
        return BtnExaminar;
    }

    public void setBtnExaminar(JButton BtnExaminar) {
        this.BtnExaminar = BtnExaminar;
    }

    public JLabel getLblFoto() {
        return LblFoto;
    }

    public void setLblFoto(JLabel LblFoto) {
        this.LblFoto = LblFoto;
    }

    public JComboBox<String> getComboSeccionProducto() {
        return ComboSeccionProducto;
    }

    public void setComboSeccionProducto(JComboBox<String> ComboSeccionProducto) {
        this.ComboSeccionProducto = ComboSeccionProducto;
    }

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public void setBtnActualizar(JButton btnActualizar) {
        this.btnActualizar = btnActualizar;
    }

    public JComboBox<String> getComboNombreProductoVen() {
        return ComboNombreProductoVen;
    }

    public void setComboNombreProductoVen(JComboBox<String> ComboNombreProductoVen) {
        this.ComboNombreProductoVen = ComboNombreProductoVen;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgDialogoProductos = new javax.swing.JDialog();
        btnAceptarP = new javax.swing.JButton();
        btnCancelarP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtPrecioProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SpnCantidadProducto = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionProducto = new javax.swing.JTextArea();
        LblFoto = new javax.swing.JLabel();
        BtnExaminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboSeccionProducto = new javax.swing.JComboBox<>();
        ComboNombreProductoVen = new javax.swing.JComboBox<>();
        TxtIdProductot = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCrearProducto = new javax.swing.JButton();
        btnEditarProdcuto = new javax.swing.JButton();
        btnRemoverProducto = new javax.swing.JButton();
        TxtBuscarProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnImprimirProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();

        btnAceptarP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-guardar-30.png"))); // NOI18N
        btnAceptarP.setText("ACEPTAR");

        btnCancelarP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cancelar-30.png"))); // NOI18N
        btnCancelarP.setText("CANCELAR");

        jLabel2.setText("ID Producto:");

        jLabel8.setText("Cantidad");

        jLabel9.setText("Descripción:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Precio:");

        SpnCantidadProducto.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtDescripcionProducto.setColumns(20);
        txtDescripcionProducto.setLineWrap(true);
        txtDescripcionProducto.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionProducto);

        LblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BtnExaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-añadir-imagen-20.png"))); // NOI18N
        BtnExaminar.setText("Examinar");

        jLabel5.setText("Foto");

        jLabel6.setText("Seccion Producto:");

        ComboSeccionProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Vegetales", "Frutas", "Helado", "Bebidas Gaseosas", "Bebidas Alcohólicas", "Lácteos" }));

        javax.swing.GroupLayout dlgDialogoProductosLayout = new javax.swing.GroupLayout(dlgDialogoProductos.getContentPane());
        dlgDialogoProductos.getContentPane().setLayout(dlgDialogoProductosLayout);
        dlgDialogoProductosLayout.setHorizontalGroup(
            dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnAceptarP)
                        .addGap(71, 71, 71)
                        .addComponent(btnCancelarP)
                        .addContainerGap())
                    .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                        .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(63, 63, 63)
                        .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ComboNombreProductoVen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SpnCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ComboSeccionProducto, 0, 153, Short.MAX_VALUE)
                                        .addComponent(TxtPrecioProducto))
                                    .addComponent(TxtIdProductot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDialogoProductosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDialogoProductosLayout.createSequentialGroup()
                                        .addComponent(LblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDialogoProductosLayout.createSequentialGroup()
                                        .addComponent(BtnExaminar)
                                        .addGap(34, 34, 34))))
                            .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel5)
                                .addContainerGap())))))
        );
        dlgDialogoProductosLayout.setVerticalGroup(
            dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgDialogoProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TxtIdProductot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5))
                    .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboSeccionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                        .addComponent(LblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExaminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel9))
                            .addGroup(dlgDialogoProductosLayout.createSequentialGroup()
                                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboNombreProductoVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SpnCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(dlgDialogoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptarP)
                            .addComponent(btnCancelarP))
                        .addGap(25, 25, 25))))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(206, 224, 175));

        btnCrearProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCrearProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-crear-30.png"))); // NOI18N
        btnCrearProducto.setText("Crear");

        btnEditarProdcuto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditarProdcuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-product-30.png"))); // NOI18N
        btnEditarProdcuto.setText("Editar");

        btnRemoverProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemoverProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-eliminar-30_1.png"))); // NOI18N
        btnRemoverProducto.setText("Remover");

        jLabel1.setText("Buscar");

        btnImprimirProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnImprimirProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-desfibradora-30.png"))); // NOI18N
        btnImprimirProducto.setText("Imprimir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(TxtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnCrearProducto)
                .addGap(28, 28, 28)
                .addComponent(btnEditarProdcuto)
                .addGap(28, 28, 28)
                .addComponent(btnRemoverProducto)
                .addGap(29, 29, 29)
                .addComponent(btnImprimirProducto)
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverProducto)
                    .addComponent(btnEditarProdcuto)
                    .addComponent(btnCrearProducto)
                    .addComponent(TxtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnImprimirProducto))
                .addGap(19, 19, 19))
        );

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "Nombre", "Precio", "Cantidad", "Foto", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel3.setBackground(new java.awt.Color(206, 224, 175));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-actualizar-30.png"))); // NOI18N
        btnActualizar.setText("Actualizar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExaminar;
    private javax.swing.JComboBox<String> ComboNombreProductoVen;
    private javax.swing.JComboBox<String> ComboSeccionProducto;
    private javax.swing.JLabel LblFoto;
    private javax.swing.JSpinner SpnCantidadProducto;
    private javax.swing.JTextField TxtBuscarProducto;
    private javax.swing.JTextField TxtIdProductot;
    private javax.swing.JTextField TxtPrecioProducto;
    private javax.swing.JButton btnAceptarP;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelarP;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnEditarProdcuto;
    private javax.swing.JButton btnImprimirProducto;
    private javax.swing.JButton btnRemoverProducto;
    private javax.swing.JDialog dlgDialogoProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextArea txtDescripcionProducto;
    // End of variables declaration//GEN-END:variables
}
