/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.secciones;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JSpinner;
import javax.swing.JTable;

/**
 *
 * @author DELL
 */
public class PanelFrutas extends javax.swing.JPanel {

    /**
     * Creates new form PanelFrutas
     */
    public PanelFrutas() {
        initComponents();
    }

    public JButton getBtnMandarina() {
        return BtnMandarina;
    }

    public void setBtnMandarina(JButton BtnMandarina) {
        this.BtnMandarina = BtnMandarina;
    }

    public JButton getBtnNaranja() {
        return BtnNaranja;
    }

    public void setBtnNaranja(JButton BtnNaranja) {
        this.BtnNaranja = BtnNaranja;
    }

    public JButton getBtnPapaya() {
        return BtnPapaya;
    }

    public void setBtnPapaya(JButton BtnPapaya) {
        this.BtnPapaya = BtnPapaya;
    }

    public JButton getBtnSandia() {
        return BtnSandia;
    }

    public void setBtnSandia(JButton BtnSandia) {
        this.BtnSandia = BtnSandia;
    }

    public JDialog getDialogoProductosF() {
        return DialogoProductosF;
    }

    public void setDialogoProductosF(JDialog DialogoProductosF) {
        this.DialogoProductosF = DialogoProductosF;
    }
    

    public JButton getBtnAceptarPF() {
        return BtnAceptarPF;
    }

    public void setBtnAceptarPF(JButton BtnAceptarPF) {
        this.BtnAceptarPF = BtnAceptarPF;
    }

    public JButton getBtnCancelarPF() {
        return BtnCancelarPF;
    }

    public void setBtnCancelarPF(JButton BtnCancelarPF) {
        this.BtnCancelarPF = BtnCancelarPF;
    }

    public JSpinner getSpinerCantidadFruta() {
        return SpinerCantidadFruta;
    }

    public void setSpinerCantidadFruta(JSpinner SpinerCantidadFruta) {
        this.SpinerCantidadFruta = SpinerCantidadFruta;
    }

    public JTable getTablaProductoFru() {
        return TablaProductoFru;
    }

    public void setTablaProductoFru(JTable TablaProductoFru) {
        this.TablaProductoFru = TablaProductoFru;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoProductosF = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductoFru = new javax.swing.JTable();
        SpinerCantidadFruta = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        BtnAceptarPF = new javax.swing.JButton();
        BtnCancelarPF = new javax.swing.JButton();
        BtnPapaya = new javax.swing.JButton();
        BtnSandia = new javax.swing.JButton();
        BtnNaranja = new javax.swing.JButton();
        BtnMandarina = new javax.swing.JButton();

        TablaProductoFru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD", "FOTO"
            }
        ));
        jScrollPane1.setViewportView(TablaProductoFru);

        SpinerCantidadFruta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel1.setText("Cantidad:");

        BtnAceptarPF.setText("Aceptar");

        BtnCancelarPF.setText("Cancelar");

        javax.swing.GroupLayout DialogoProductosFLayout = new javax.swing.GroupLayout(DialogoProductosF.getContentPane());
        DialogoProductosF.getContentPane().setLayout(DialogoProductosFLayout);
        DialogoProductosFLayout.setHorizontalGroup(
            DialogoProductosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoProductosFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(SpinerCantidadFruta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(DialogoProductosFLayout.createSequentialGroup()
                .addGroup(DialogoProductosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoProductosFLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogoProductosFLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(BtnAceptarPF)
                        .addGap(68, 68, 68)
                        .addComponent(BtnCancelarPF)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        DialogoProductosFLayout.setVerticalGroup(
            DialogoProductosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoProductosFLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(DialogoProductosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinerCantidadFruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(DialogoProductosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptarPF)
                    .addComponent(BtnCancelarPF))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        BtnPapaya.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPapaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Papaya.png"))); // NOI18N
        BtnPapaya.setText("Papaya");
        BtnPapaya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPapaya.setPreferredSize(new java.awt.Dimension(123, 120));
        BtnPapaya.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnSandia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSandia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Sandia.png"))); // NOI18N
        BtnSandia.setText("Sandia");
        BtnSandia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSandia.setPreferredSize(new java.awt.Dimension(123, 120));
        BtnSandia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnNaranja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnNaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Naranja.png"))); // NOI18N
        BtnNaranja.setText("Naranja");
        BtnNaranja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnNaranja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnMandarina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnMandarina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Mandarina.png"))); // NOI18N
        BtnMandarina.setText("Mandarina");
        BtnMandarina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMandarina.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnMandarina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPapaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(BtnSandia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(BtnNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnSandia, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(BtnNaranja, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addComponent(BtnPapaya, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(BtnMandarina, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptarPF;
    private javax.swing.JButton BtnCancelarPF;
    private javax.swing.JButton BtnMandarina;
    private javax.swing.JButton BtnNaranja;
    private javax.swing.JButton BtnPapaya;
    private javax.swing.JButton BtnSandia;
    private javax.swing.JDialog DialogoProductosF;
    private javax.swing.JSpinner SpinerCantidadFruta;
    private javax.swing.JTable TablaProductoFru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
