/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.secciones;

import javax.swing.JButton;

/**
 *
 * @author DELL
 */
public class VistaGeneralProductos extends javax.swing.JPanel {

    /**
     * Creates new form VistaGeneralProductos
     */
    public VistaGeneralProductos() {
        initComponents();
    }

    public JButton getBtnCocaColaPG() {
        return BtnCocaColaPG;
    }

    public void setBtnCocaColaPG(JButton BtnCocaColaPG) {
        this.BtnCocaColaPG = BtnCocaColaPG;
    }

    public JButton getBtnFantaPG() {
        return BtnFantaPG;
    }

    public void setBtnFantaPG(JButton BtnFantaPG) {
        this.BtnFantaPG = BtnFantaPG;
    }

    public JButton getBtnGinebraPG() {
        return BtnGinebraPG;
    }

    public void setBtnGinebraPG(JButton BtnGinebraPG) {
        this.BtnGinebraPG = BtnGinebraPG;
    }

    public JButton getBtnIncaKolaPG() {
        return BtnIncaKolaPG;
    }

    public void setBtnIncaKolaPG(JButton BtnIncaKolaPG) {
        this.BtnIncaKolaPG = BtnIncaKolaPG;
    }

    public JButton getBtnLechePG() {
        return BtnLechePG;
    }

    public void setBtnLechePG(JButton BtnLechePG) {
        this.BtnLechePG = BtnLechePG;
    }

    public JButton getBtnPepsiPG() {
        return BtnPepsiPG;
    }

    public void setBtnPepsiPG(JButton BtnPepsiPG) {
        this.BtnPepsiPG = BtnPepsiPG;
    }

    public JButton getBtnQuesoPG() {
        return BtnQuesoPG;
    }

    public void setBtnQuesoPG(JButton BtnQuesoPG) {
        this.BtnQuesoPG = BtnQuesoPG;
    }

    public JButton getBtnRonPG() {
        return BtnRonPG;
    }

    public void setBtnRonPG(JButton BtnRonPG) {
        this.BtnRonPG = BtnRonPG;
    }

    public JButton getBtnSpritePG() {
        return BtnSpritePG;
    }

    public void setBtnSpritePG(JButton BtnSpritePG) {
        this.BtnSpritePG = BtnSpritePG;
    }

    public JButton getBtnTequilaPG() {
        return BtnTequilaPG;
    }

    public void setBtnTequilaPG(JButton BtnTequilaPG) {
        this.BtnTequilaPG = BtnTequilaPG;
    }

    public JButton getBtnVodkaPG() {
        return BtnVodkaPG;
    }

    public void setBtnVodkaPG(JButton BtnVodkaPG) {
        this.BtnVodkaPG = BtnVodkaPG;
    }

    public JButton getBtnWhiskyPG() {
        return BtnWhiskyPG;
    }

    public void setBtnWhiskyPG(JButton BtnWhiskyPG) {
        this.BtnWhiskyPG = BtnWhiskyPG;
    }

    public JButton getBtnYogurPG() {
        return BtnYogurPG;
    }

    public void setBtnYogurPG(JButton BtnYogurPG) {
        this.BtnYogurPG = BtnYogurPG;
    }

    public JButton getBtnZhumirPG() {
        return BtnZhumirPG;
    }

    public void setBtnZhumirPG(JButton BtnZhumirPG) {
        this.BtnZhumirPG = BtnZhumirPG;
    }

    public JButton getBtnCoñacPG() {
        return BtnCoñacPG;
    }

    public void setBtnCoñacPG(JButton BtnCoñacPG) {
        this.BtnCoñacPG = BtnCoñacPG;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        BtnCocaColaPG = new javax.swing.JButton();
        BtnSpritePG = new javax.swing.JButton();
        BtnPepsiPG = new javax.swing.JButton();
        BtnIncaKolaPG = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnFantaPG = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnVodkaPG = new javax.swing.JButton();
        BtnQuesoPG = new javax.swing.JButton();
        BtnYogurPG = new javax.swing.JButton();
        BtnLechePG = new javax.swing.JButton();
        BtnTequilaPG = new javax.swing.JButton();
        BtnRonPG = new javax.swing.JButton();
        BtnGinebraPG = new javax.swing.JButton();
        BtnWhiskyPG = new javax.swing.JButton();
        BtnCoñacPG = new javax.swing.JButton();
        BtnZhumirPG = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(222, 233, 234));

        BtnCocaColaPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCocaColaPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/CocaCola.png"))); // NOI18N
        BtnCocaColaPG.setText("Coca Cola");
        BtnCocaColaPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCocaColaPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnSpritePG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSpritePG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Sprite.png"))); // NOI18N
        BtnSpritePG.setText("Sprite");
        BtnSpritePG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSpritePG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnPepsiPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPepsiPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Pepsi.png"))); // NOI18N
        BtnPepsiPG.setText("Pepsi");
        BtnPepsiPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPepsiPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnIncaKolaPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnIncaKolaPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/IncaKola.png"))); // NOI18N
        BtnIncaKolaPG.setText("Inca Kola");
        BtnIncaKolaPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnIncaKolaPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sección Bebidas gaseosas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnFantaPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnFantaPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Fanta.png"))); // NOI18N
        BtnFantaPG.setText("Fanta");
        BtnFantaPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnFantaPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sección Lácteos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Sección Bebidas Alcohólicas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnVodkaPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnVodkaPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/VodkaAlco.png"))); // NOI18N
        BtnVodkaPG.setText("Vodka");
        BtnVodkaPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVodkaPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnQuesoPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnQuesoPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Queso.png"))); // NOI18N
        BtnQuesoPG.setText("Queso");
        BtnQuesoPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnQuesoPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnYogurPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnYogurPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Yogurt.png"))); // NOI18N
        BtnYogurPG.setText("Yogur");
        BtnYogurPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnYogurPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnLechePG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnLechePG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/Leche.png"))); // NOI18N
        BtnLechePG.setText("Leche");
        BtnLechePG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLechePG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnTequilaPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnTequilaPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/TequilaAlco.png"))); // NOI18N
        BtnTequilaPG.setText("Tequila");
        BtnTequilaPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnTequilaPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnRonPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnRonPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/RonAlco.png"))); // NOI18N
        BtnRonPG.setText("Ron");
        BtnRonPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRonPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnGinebraPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnGinebraPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/GinebraAlco.png"))); // NOI18N
        BtnGinebraPG.setText("Ginebra");
        BtnGinebraPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGinebraPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnWhiskyPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnWhiskyPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/WhiskyAlco.png"))); // NOI18N
        BtnWhiskyPG.setText("Whisky");
        BtnWhiskyPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnWhiskyPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnCoñacPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCoñacPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/CoñacAlco.png"))); // NOI18N
        BtnCoñacPG.setText("Coñac");
        BtnCoñacPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCoñacPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BtnZhumirPG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnZhumirPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/secciones/Img/ZhumirAlco.png"))); // NOI18N
        BtnZhumirPG.setText("ZHUMIR");
        BtnZhumirPG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnZhumirPG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnIncaKolaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(BtnFantaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnCocaColaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(BtnSpritePG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnLechePG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(BtnYogurPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnQuesoPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnPepsiPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnVodkaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnWhiskyPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnGinebraPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnCoñacPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnTequilaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnRonPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BtnZhumirPG, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSpritePG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPepsiPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCocaColaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIncaKolaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFantaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnYogurPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnQuesoPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLechePG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVodkaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTequilaPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRonPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnWhiskyPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGinebraPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCoñacPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(BtnZhumirPG, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCocaColaPG;
    private javax.swing.JButton BtnCoñacPG;
    private javax.swing.JButton BtnFantaPG;
    private javax.swing.JButton BtnGinebraPG;
    private javax.swing.JButton BtnIncaKolaPG;
    private javax.swing.JButton BtnLechePG;
    private javax.swing.JButton BtnPepsiPG;
    private javax.swing.JButton BtnQuesoPG;
    private javax.swing.JButton BtnRonPG;
    private javax.swing.JButton BtnSpritePG;
    private javax.swing.JButton BtnTequilaPG;
    private javax.swing.JButton BtnVodkaPG;
    private javax.swing.JButton BtnWhiskyPG;
    private javax.swing.JButton BtnYogurPG;
    private javax.swing.JButton BtnZhumirPG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
